### ISSUE TITLE
LoL

### ISSUE THREAD

**Issue by Jelly9912** [NikoTBC/ExtendedCreative#1]
Why did you do that:
item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));
  item::addCreativeItem(Item::get(403, 0));

**Comment by NikoTBC** [comment]
I do that to add a lot of empty enchanted books
